services:

  # USER SERVICE
  user_grpc:
    container_name: user_grpc
    ports:
      - "8083:8083"
    environment:
      - APP_PORT=:8083
      - DIAL_AUTH_ENDPOINT=auth_grpc:8081 
    build:
      context: .
      dockerfile: "./user_service/grpc/Dockerfile"
    restart: on-failure
    depends_on:
    - db_user
  user_gateway:
    container_name: user_gateway
    environment:
      - APP_PORT=:8082
      - GRPC_ENDPOINT=user_grpc:8083
    build:
      context: .
      dockerfile: "./user_service/gateway/Dockerfile"
    depends_on:
      - user_grpc

  # AUTH SERVICE
  auth_grpc:
    container_name: auth_grpc
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=:8081
      - DIAL_USER_ENDPOINT=user_grpc:8083
      - JWT_SECRET_KEY=MjqhdctsWx3VGjInxLLjMJsrxTdhzdiHQlvWtGmTEXUOMCa0uGen5XkUehWYZYici917wM5jl3ntMadDAWt7BfxQh1FyXCTOoMxrtpGOEMnhUgZNQIhRbgPsN0gDJPHnn3oegs8LpONQZqdE9IfVO1r6czdwXaoXL3XBSbC3MTQVbnScFjPxcakOAlkDtfzs2TRWNmQxH8sB0nb3HCIhBQz9sc6IcSSREYDEjIQaibHocqs7mEXNkX0XmSDrkbqixeF05z2oJpfk5lwNQDQ72x3F0WDaw7VSpVDZqHm4hWpPIZHDQgBKuzGZ0XKPRJ1W6uNPHq6u5OMRkyihd5U9cWtUTUBaCwvlrmkvuDmz2CKuV7Q5NXcL60lM7PEF7CB7fQHS50B8we2nTq5P8eGm8xfwtO9xSvZunzjKdf8gzTQWKs6kBoRlfoefbiXpkB4iZeVZCS3YqHmEkK3cIVAKkSeq9QXyg8FOdWc3YyrhKKaIw5yuBZffJ0Pvs3yqGGy0naTC7ADehEKJF4sul21OIJ5B2ppCBYA3n7RIwp0VWLBOhtzj2LlyzkCpq2JXdqHkB763xxQpPeUyZuLBz9NAc94n62tiIHVC3puIDGzmzgCm37fO4TydEofqs8Vcs9BhHRub4LkG2MgKyMyO4zbQorTRr76cSjVcxuigubSrWz72z9AKmxvWg4nTVihEa7v8ouSRdsKIhuOY47aF3O5CJlzoIKpN2YopljcBXlnV8essV5
    build:
      context: .
      dockerfile: "./auth_service/grpc/Dockerfile"
    restart: on-failure
    depends_on:
    - user_grpc
  auth_gateway:
    container_name: auth_gateway
    environment:
      - APP_PORT=:8080
      - GRPC_ENDPOINT=auth_grpc:8081
    build:
      context: .
      dockerfile: "./auth_service/gateway/Dockerfile"
    depends_on:
      - auth_grpc

  # CHAT SERVICE
  chat_grpc:
    container_name: chat_grpc
    ports:
      - "8085:8085"
    environment:
      - DIAL_AUTH_ENDPOINT=auth_grpc:8081
      - APP_PORT=:8085
    build:
      context: .
      dockerfile: "./chat_service/grpc/Dockerfile"
    depends_on:
      - user_grpc
      - auth_grpc
  chat_gateway:
    container_name: chat_gateway
    environment:
      - APP_PORT=:8084
      - GRPC_ENDPOINT=chat_grpc:8085
    build:
      context: .
      dockerfile: "./chat_service/gateway/Dockerfile"
    depends_on:
      - chat_grpc

  # PROXY SERVER
  proxy_server:
    container_name: proxy_server
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - user_gateway
      - user_grpc
      - auth_gateway
      - auth_grpc
      - db_user
      - chat_grpc
      - chat_gateway

  # DATABASE
  db_user:
    container_name: db_user
    image: postgres:latest
    environment:
      POSTGRES_DB: user_service
      POSTGRES_PASSWORD: 12345678
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
