services:

  # USER SERVICE
  user_grpc:
    container_name: user_grpc
    build:
      context: .
      dockerfile: "./userproxy/grpc/Dockerfile"
    depends_on:
    - db_user
  user_gateway:
    container_name: user_gateway
    build:
      context: .
      dockerfile: "./userproxy/gateway/Dockerfile"
    depends_on:
      - user_grpc

  # AUTH SERVICE
  auth_grpc:
    container_name: auth_grpc
    build:
      context: .
      dockerfile: "./authproxy/grpc/Dockerfile"
    depends_on:
    - user_grpc
  auth_gateway:
    container_name: auth_gateway
    build:
      context: .
      dockerfile: "./authproxy/gateway/Dockerfile"
    depends_on:
      - auth_grpc

  # DATABASE
  db_user:
    container_name: db_user
    image: postgres:latest
    environment:
      POSTGRES_DB: user_service
      POSTGRES_PASSWORD: 12345678
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5