services:
  # auth_gateway:
  #   container_name: auth_gateway
  #   build:
  #     context: "./authproxy/gateway/"
  #     dockerfile: Dockerfile
  #   image: "auth_gateway:1.0.0"
  #   ports:
  #     - "8080"
  # auth_grpc:
  #   container_name: auth_grpc
  #   build:
  #     context: "./authproxy/grpc"
  #     dockerfile: Dockerfile
  #   image: "auth_grpc:1.0.0"
  #   ports:
  #     - "8081"
  # user_gateway:
  #   container_name: user_gateway
  #   build:
  #     context: "./userproxy/gateway"
  #     dockerfile: Dockerfile
  #   image: "user_gateway:1.0.0"
  #   ports:
  #     - "8082"
  # user_grpc:
  #   container_name: user_grpc
  #   build:
  #     context: "./userproxy/grpc"
  #     dockerfile: Dockerfile
  #   image: "user_grpc:1.0.0"
  #   ports:
  #     - "8083"
  proxy:
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    image: nginx:latest
    ports:
      - "8080:80"